const http=require('http'),fs=require('fs'),path=require('path');
const {WebSocketServer}=require('ws');
const root=path.join(__dirname,'public');
const server=http.createServer((req,res)=>{let u=decodeURIComponent(req.url.split('?')[0]); if(u==='/')u='/index.html'; const f=path.join(root,u); if(!f.startsWith(root)||!fs.existsSync(f))return res.writeHead(404).end('Not found'); const ext=path.extname(f); const types={'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.png':'image/png'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'});fs.createReadStream(f).pipe(res);});
const wss=new WebSocketServer({server});const rooms=new Map();
function send(ws,o){if(ws.readyState===1)ws.send(JSON.stringify(o));}
function snapshot(room){return [...(rooms.get(room)?.players?.values()||[])];}
wss.on('connection',ws=>{ws.on('message',buf=>{let m;try{m=JSON.parse(buf)}catch{return}; if(m.type==='teacher'){ws.role='teacher';ws.room=m.room; if(!rooms.has(m.room))rooms.set(m.room,{teacher:ws,players:new Map()}); rooms.get(m.room).teacher=ws; send(ws,{type:'snapshot',players:snapshot(m.room)}); return} if(m.type==='student'){ws.role='student';ws.room=m.room;ws.team=m.team;let r=rooms.get(m.room);if(!r)return send(ws,{type:'error',message:'Phòng không tồn tại'});r.players.set(m.team,{team:m.team,score:0,stage:1,finished:false,time:null,elapsed:0,gameStarted:false});send(ws,{type:'snapshot',players:snapshot(m.room)}); if(r.teacher)send(r.teacher,{type:'state',...r.players.get(m.team)});return} if(m.type==='state'&&ws.role==='student'){ws.team=m.team;let r=rooms.get(ws.room);if(!r)return;r.players.set(m.team,m);if(r.teacher)send(r.teacher,{type:'state',...m});}});ws.on('close',()=>{if(ws.role==='teacher'){let r=rooms.get(ws.room);if(r&&r.teacher===ws)r.teacher=null}else if(ws.role==='student'){let r=rooms.get(ws.room);if(r&&r.players.has(ws.team)){let p=r.players.get(ws.team);p.online=false;if(r.teacher)send(r.teacher,{type:'state',...p});}}});});
const port=process.env.PORT||3000;server.listen(port,()=>console.log('Sulfur game running on '+port));
